import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#4a463f",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#f2eeff",
        "primary-fixed": "#ffdad4",
        "on-primary-fixed": "#400100",
        "surface": "#fcf8ff",
        "surface-container-high": "#e9e5ff",
        "inverse-primary": "#ffb4a7",
        "surface-variant": "#e3dffe",
        "error": "#ba1a1a",
        "on-background": "#1a1930",
        "outline": "#916f69",
        "outline-variant": "#e5bdb7",
        "on-secondary": "#ffffff",
        "surface-dim": "#dad7f6",
        "secondary-fixed": "#e9e1e0",
        "surface-container": "#efebff",
        "tertiary": "#45423a",
        "surface-container-highest": "#e3dffe",
        "on-primary-container": "#ffc2b8",
        "on-tertiary-fixed": "#1e1b15",
        "primary-fixed-dim": "#ffb4a7",
        "on-error": "#ffffff",
        "on-primary": "#ffffff",
        "on-surface-variant": "#5c403b",
        "tertiary-fixed": "#e8e2d7",
        "surface-bright": "#fcf8ff",
        "secondary-fixed-dim": "#ccc5c4",
        "background": "#fcf8ff",
        "tertiary-container": "#5d5951",
        "on-secondary-fixed-variant": "#4a4645",
        "primary-container": "#b50a01",
        "error-container": "#ffdad6",
        "on-tertiary-container": "#d6d0c6",
        "on-secondary-fixed": "#1e1b1b",
        "secondary": "#625d5d",
        "secondary-container": "#e6dedd",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#bd1306",
        "surface-container-low": "#f6f2ff",
        "inverse-surface": "#2f2e46",
        "on-surface": "#1a1930",
        "tertiary-fixed-dim": "#ccc6bb",
        "primary": "#890400",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#920500",
        "on-secondary-container": "#666161",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        "stack-lg": "48px",
        "margin-desktop": "120px",
        "stack-md": "24px",
        "margin-mobile": "24px",
        "stack-sm": "8px",
        "section-padding": "160px",
      },
      fontFamily: {
        "display-lg-mobile": ["var(--font-epilogue)"],
        "display-2xl": ["var(--font-epilogue)"],
        "display-lg": ["var(--font-epilogue)"],
        "body-lg": ["var(--font-dm-sans)"],
        "body-md": ["var(--font-dm-sans)"],
        "label-mono": ["var(--font-jetbrains-mono)"],
        "headline-md": ["var(--font-epilogue)"],
      },
      fontSize: {
        "display-lg-mobile": ["48px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "display-2xl": ["120px", { lineHeight: "110px", letterSpacing: "-0.04em", fontWeight: "800" }],
        "display-lg": ["72px", { lineHeight: "72px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "body-lg": ["20px", { lineHeight: "32px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-mono": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "headline-md": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
export default config;
